### ISSUE TITLE
Converter is broken with PyLint v2.5.2 (Python v3.6.9)

### ISSUE THREAD

**Issue by ahogen** [aroden-crowdstrike/pylint2junit#3]
I'm generating "parseable" output from pylint. Then using the `pylint2junit` converter afterwards. But I keep getting 

```bash
$ pylint2junit -i pylint_out.txt -o pylint_out.junit.xml
Traceback (most recent call last):
  File "/home/alex/.local/bin/pylint2junit", line 8, in <module>
    sys.exit(main())
  File "/home/alex/.local/lib/python3.6/site-packages/pylint2junit/__main__.py", line 49, in main
    parse_input_lines(input_lines),
  File "/home/alex/.local/lib/python3.6/site-packages/pylint2junit/tojunit.py", line 23, in pylint_to_junit
    modules = list(modules)
  File "/home/alex/.local/lib/python3.6/site-packages/pylint2junit/parse.py", line 56, in parse_input_lines
    _lines_to_pylint(cur_line_list)
  File "/home/alex/.local/lib/python3.6/site-packages/pylint2junit/parse.py", line 91, in _lines_to_pylint
    raise NotImplementedError("Undetected format")
NotImplementedError: Undetected format
```

This seems to be because of outdated regex in the code. The [message format expected](https://github.com/aroden-crowdstrike/pylint2junit/blob/ba299708385d5db04e964d9ff69727ba0c990488/pylint2junit/parse.py#L76-L83) in this library doesn't match what pylint v2.5.2 generates. By default, it seems pylint generates something like the following:

```text
src/cppcheck_codeclimate.py:31: [C0301(line-too-long), ] Line too long (95/81)
```

I can fix the message format in my `.pylintrc` with...

```python
# Template used to display messages. This is a python new-style format string
# used to format the message information. See doc for all details
msg-template='{path}:{line}:{column}: {msg_id}: {msg} ({symbol})'
```

However, I still get that "undetected" error because in my pylint output, there are only 66 dashes (`-`) before the score print. [Pylint2Junit expects exactly 67](https://github.com/aroden-crowdstrike/pylint2junit/blob/ba299708385d5db04e964d9ff69727ba0c990488/pylint2junit/parse.py#L10), no more, no less.

Without hacking into pylint or this library, it seems this is broken. :disappointed:

**Comment by ahogen** [comment]
Hmm. I must have been tired and/or misconfigured something. The message format seems fine.

The second issue, the number of dashes before the pylint Score, is still a problem. Since I think we're just looking for a line that contains nothing but a bunch of dashes, I feel like [the regex here](https://github.com/aroden-crowdstrike/pylint2junit/blob/ba299708385d5db04e964d9ff69727ba0c990488/pylint2junit/parse.py#L10) can be loosed up a little bit.

```diff
- _REPORT_RE = re.compile(r'^-{67}')
+ _REPORT_RE = re.compile(r'^-{30,}$')
```

**Comment by DamianSepczuk** [comment]
It also can't handle parseable output with enabled reports. Without modifying `pylint2junit`'s source code, you can modify the parseable output so that `pylint2junit` is happy:

```shell
pylint2junit \
    --input=<(sed -E \
       '/^Report/,/-{30,}/{'\
'          /^-{30,}/!d;'\
'          /^-{30,}/s//'"$(printf %.s- {1..67})"'/'\
'      }'\
       pylint_parseable.txt)\
    --output=pylint_junit.xml
```

**Comment by wmbolle** [comment]
Please, see my pull requests #4 and #5 that all together successfully address the problems described here. I am using pylint 2.5.3.
